export default ActionsName = {
  setMedecinData: 'setMedecinData',
  resetMedecinData: 'resetMedecinData',
  setPatientData: 'setPatientData',
  resetPatientData: 'resetPatientData',
  setMaladieData: 'setMaladieData',
  addMaladieData: 'addMaladieData',
  resetMaladieData: 'resetMaladieData',
  setPatientsListData: 'setPatientsListData',
  resetPatientsListData: 'resetPatientsListData',
  connecte: 'connect',
  disconnect: 'disconnect',
  finishSplash: 'finishSplash',
  changeStatus: 'changeStatus',
};
